### ISSUE TITLE
Installation Script Clears Error Messages Before Configuration 

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AM-Application-Manager#103]
**Description:**

After the installation script reaches the "◆ RUNNING THE INSTALLATION SCRIPT FOR" step, all error messages are getting cleared out before reaching the "◆ CONFIGURING "***" " step. This makes it challenging for users to diagnose installation issues and understand what went wrong.

**Problem:**

The stderr messages are being cleared out, and users are unable to read error messages generated during the installation process, hindering proper diagnosis of installation problems.

**Suggestion:**

It is recommended to modify the installation script so that stderr messages are not cleared out before reaching the "◆ CONFIGURING "***"" step. This will enable users to identify and troubleshoot issues during the installation process more effectively.

**Steps to Reproduce:**
1. Execute the installation script.
2. Observe that error messages generated during the installation process are cleared out before reaching the "◆ CONFIGURING "***"" step.

**Expected Behavior:**

Error messages should be retained and displayed to users even after the "◆ RUNNING THE INSTALLATION SCRIPT FOR" step, allowing for proper diagnosis of any installation issues.

**Environment:**
- Operating System: Archlinux
- Shell: ZSH
- Version of the application: 5.3.1-5

**Additional Information:**
![2024-01-18_16-05](https://github.com/ivan-hc/AM-Application-Manager/assets/45564804/5c01f630-8b62-43b2-ac4b-6bf82baac302)

**Comment by ivan-hc** [comment]
This is a douped issue you have already opened and I've closed at https://github.com/ivan-hc/AppMan/issues/28 

Please choose only one of the two repositorie, do not copy/paste/spam the issue on both the repositories.

Thank you
