### ISSUE TITLE
Add GitHub Personal Access Token (PAT) as an Option for API Requests

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AM-Application-Manager#104]
## Description
When using the `am` tool on a shared network, there are instances where the IP gets rate-limited by the GitHub API, leading to installation failures with the following error: "ERROR 403: rate limit exceeded."

To address this issue and improve user experience, I propose adding an option to append a header with the GitHub Personal Access Token (PAT) for every request made to `api.github.com`. This will allow users to authenticate their requests and avoid rate limiting issues.

## Suggested Enhancement
Introduce a new command-line option or configuration parameter that allows users to specify their GitHub PAT. This PAT will be appended as a header for every API request made by `appman`.

## Example Implementation
```bash
# Example command with the proposed enhancement
appman --github-pat <your_github_pat> -i <package_name>
```

## Current Workaround
I am currently using a workaround by manually modifying the API request headers in their installation script. However, having a built-in solution within `am` would greatly simplify this process and improve the overall usability.

```bash
# Current workaround function in the installation script
HeaderAuthWithGITPAT='--header "Authorization: token github_pat_**************"'
function _install_GITPAT_auth_header(){
    sed -i "s#https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
}
```

Thank you for considering this enhancement request. Let me know if you need any further clarification or information.

**Comment by ivan-hc** [comment]
This is interesting.

I can add an option "`autenticate`" in which a GH API key can be stored in the directory of the CLI (AM or AppMan), so if the file exists in that path, then the script can be patched using that key, for example:
```
echo "**********************" >> $AMPATH/ghapikey.txt
HeaderAuthWithGITPAT='--header "Authorization: token github_pat_''$(cat $AMPATH/ghapikey.txt)'"'
function _install_GITPAT_auth_header(){
    sed -i "s#https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
}
```
then we can put the function in `convert` and `install`
```
if test -f $AMPATH/ghapikey.txt; then
          _install_GITPAT_auth_header
fi
```
and we have done.

Would this be OK?

**Comment by ivan-hc** [comment]
Or better:
```
function _install_GITPAT_auth_header(){
	if test -f $AMPATH/ghapikey.txt; then
		sed -i "s#https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
	fi
}
```
and just add `_install_GITPAT_auth_header` in the options that needs it.

**Comment by ivan-hc** [comment]
I'm not familiar with AP keys, so I can't test it, but I started to wrote the option `apikey`:
```
  'apikey')

	case $2 in
	'') echo " USAGE: $AMCLI $1 [ARGUMENT]"; exit;;
	esac

	while [ -n "$1" ]; do
		rm -f $AMPATH/apikey
		echo "$2" >> $AMPATH/apikey
	done

	shift
	;;
```
it is brief, it does not do much... is it possible to check if an API key is a valid one?

**Comment by DLopezJr** [comment]
You can interact with the API using a tool like `curl`.

**Comment by ivan-hc** [comment]
Hi @DLopezJr , as I said I'm not familiar with API key usage, so how should I check it using `curl` (that is a default dependency of AM)?

**Comment by DLopezJr** [comment]
I'm not too familiar with the API, but you could do a -X GET request to the API path. The return value could then be validated using  a standard `if` statement in shell. 

I'm a bit busy with the refactor process right now, but I could dedicate some time to this next week.

**Comment by ivan-hc** [comment]
This is a preview of the changes between the current version and the one proposed here

https://www.diffchecker.com/up2S6eyg/

but I need to improve the check of valid keys. So `if` the key if valid, `then` `echo "$2" >> $AMPATH/apikey`, `else` don't do anything. This will be the scheme in my mind.

I added `sed -i "s#https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg` in the options `convert` and `install`, but if the environment variable `$HeaderAuthWithGITPAT` is empty, then will be added only a space in the script during the patching of the latter.

As you can see, there is not much to do here.

@nazdridoy I'm waiting for your feedback.

**Comment by ivan-hc** [comment]
In addition, to remove the apikey file:
```
  'apikey')

	case $2 in
	'') echo " USAGE: $AMCLI $1 [ARGUMENT]"; exit;;
	esac

	while [ -n "$1" ]; do
		case $2 in
		del|delete|remove)
			rm -f $AMPATH/apikey
			echo "The file $AMPATH/apikey has been deleted"; exit;;
		*)
			rm -f $AMPATH/apikey
			echo "$2" >> $AMPATH/apikey; exit;;
		esac
	done

	shift
	;;
```
Only validation test is left.

**Comment by ivan-hc** [comment]
Replaced the fiename `apikey` with `ghapikey.txt`, so
```
  'apikey')

	case $2 in
	'') echo " USAGE: $AMCLI $1 [ARGUMENT]"; exit;;
	esac

	while [ -n "$1" ]; do
		case $2 in
		del|delete|remove)
			rm -f $AMPATH/ghapikey.txt
			echo "The file $AMPATH/ghapikey.txt has been deleted"; exit;;
		*)
			rm -f $AMPATH/ghapikey.txt
			echo "$2" >> $AMPATH/ghapikey.txt; exit;;
		esac
	done

	shift
	;;
```
and replaced the function `_install_GITPAT_auth_header` in the header with a simple `if`
```
if test -f $AMPATH/ghapikey.txt; then
		HeaderAuthWithGITPAT='--header "Authorization: token github_pat_'$(cat $AMPATH/ghapikey.txt)'"'
fi
```

**Comment by ivan-hc** [comment]
how can I generate a rendom token to test if this works?

**Comment by ivan-hc** [comment]
Thank you... but its too late. I had to create my own for this xD

The function works and is quite ready for "AM" 5.4 ;)
```
  'apikey')

	case $2 in
	'') echo " USAGE: $AMCLI $1 [ARGUMENT]"; exit;;
	esac

	while [ -n "$1" ]; do
		case $2 in
		del|delete|remove)
			rm -f $AMPATH/ghapikey.txt
			echo "The file $AMPATH/ghapikey.txt has been deleted"; exit;;
		*)
			if [[ "$2" =~ ^(gh[ps]_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})$ ]]; then
				
				test_apikey_output_with_wget=$(wget -q --header "Authorization: token $2" 'https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases' -O - | head -1)
				if [[ $(echo "$test_apikey_output_with_wget") ]]; then
					rm -f $AMPATH/ghapikey.txt
					echo "$2" >> $AMPATH/ghapikey.txt
					echo "Validation successful"
					exit
				else
					echo "ERROR: this is not a valid key!"
    					exit
    				fi
			else
    				echo "ERROR: wrong expression, validation failed!"
    				exit
			fi
			;;
		esac
	done

	shift
	;;
```

I must just adjust something here

**Comment by ivan-hc** [comment]
PS: just to be clear, the keys above are all invalid keys

**Comment by ivan-hc** [comment]
> but don't forget about '-t'|'template') &  '--rollback')

I'll do in a minor release, for nuw I must test the installation and the script to install an app does not work when it uses `sed` to replace the string you said:
```
sed -i "s# https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
```
environment variable
```
HeaderAuthWithGITPAT=' --header "Authorization: token github_pat_'$(cat $AMPATH/ghapikey.txt)'" '
```
what is wrong here?

**Comment by ivan-hc** [comment]
Found the error, is only `'$(cat $AMPATH/ghapikey.txt)'`, without "`github_pat_`"

Sorry for my ignorance, I can't do something without knowing.

**Comment by ivan-hc** [comment]
Too late, but thanks xD

**Comment by ivan-hc** [comment]
For now this release is limited to the options `install` and `convert`.

With your list of references I've also found two environment variables that I don't use anymore in the script (this is a sign that I should completelly renew the option `-t` or `template`). This is also a proof that in this moment is risky to apply this change so quickly.

And finally, about `template` I think that I'm the only user that uses it more often, normally if someone else want to merge a pull request to add applications, pushes just one app for time. I'm the only one here that uploads many scripts per time (being the author).

About `rollback`... how many time and how many apps someone should downgrade per time? All the AppImage developers on github should form a big conspiracy, uploading a shitty release in the same exact moment. You should really have to be a conspiracy theorist to believe this.

**Comment by ivan-hc** [comment]
New release https://github.com/ivan-hc/AM-Application-Manager/commit/edd9897e0aeaf36dca5d8512af70c991b160ec7b

Forgot to write it in the title :\
