### ISSUE TITLE
Add bastyon to the app list

### ISSUE THREAD

**Issue by tuchanemo** [ivan-hc/AM-Application-Manager#109]
Hi, please add the bastyon to the app list.

https://github.com/pocketnetteam/pocketnet.gui

**Comment by ivan-hc** [comment]
Done!

https://github.com/ivan-hc/AM-Application-Manager/commit/1cf12778f9b3c4b301204924b5f022cd7f8d00ae

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/a72633460c39735d0451182f1a2d68537e5a95dc
