### ISSUE TITLE
Vscodium .desktop entry named wrong.

### ISSUE THREAD

**Issue by agoodfellow123** [ivan-hc/AM-Application-Manager#112]
Hello, I just installed vscodium on my system using AM. I have realized the desktop entry didn't launched the app. I looked at the desktop file and realized it was trying to launch `codium` instead of `vscodium` after the change it started to work as expected. You should probably check that.

**Comment by ivan-hc** [comment]
What is the problem here?

Uploading simplescreenrecorder-2024-01-21_00.15.27.mp4…
