### ISSUE TITLE
Add Jazz 2 Ressurection

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM-Application-Manager#115]
This old school game can't be missed...
![Jazz2](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/4d04d46d-481e-452a-9bfd-75a8c1cc65a3/dffto58-558eec5c-d7bb-4395-ae62-990dfcbe78f9.png)

AppImages hidden in linux zip in [releases](https://github.com/deathkiller/jazz2/releases)..

Or here are latest builds [workflow](https://github.com/deathkiller/jazz2-native/actions/runs/7673475371)

**Comment by ivan-hc** [comment]
I'm trying to run it, it requires additional sources while launched.

Also the archive contains two Appimages... what of the two should I extract?

**Comment by ivan-hc** [comment]
For now I'll use jazz2.AppImage, not jazz2_sdl.AppImage

If you know what is the difference and I should correct something, please tell me:

- Added to AM https://github.com/ivan-hc/AM-Application-Manager/commit/940d413c12f072250dbcda3e4cf6a70f1e71bc85
- Added to the website https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/452412325d0ad9a694bb1a6be879d9929aa25792
