### ISSUE TITLE
Logseq Package Crashing my Arch  System 

### ISSUE THREAD

**Issue by thorrrr** [ivan-hc/AM-Application-Manager#117]
HI Guys

I have had issues today with my system not rebooting any time i update to the latest Logseq from today.

I run am -u and do it daily never had an issue the app that updates at least 2 times a week is Logseq.
I have tried 3 times and it breaks the reboot FYi not sure if i have to report to Logseq or if you guys need to know

**Comment by ivan-hc** [comment]
Hi, "AM" only provides the packages from their sources, does not supports them. Any malfunction or trouble with them is responsability of the authors.

If you use the command `am -a logseq` you're able to see the URL to the project, you can contact them at  https://github.com/logseq/logseq to report the issue.

**Comment by ivan-hc** [comment]
@thorrrr However, if I can give my opinion (I state that I don't know what this application does), from the way you told me, there seems to be some active system daemon or other background services that refer to the app and that they have problems recognizing the new version, once changed. Typically, on Linux, this turns into a slowdown with messages like "a start job is running for..." or something like that. Like this:

![Istantanea_2024-01-31_19-31-10 png](https://github.com/ivan-hc/AM-Application-Manager/assets/88724353/98508d64-f63d-4e55-a96e-12bffb051153)

You should check the logs.

Greetings
