### ISSUE TITLE
Don't use less by default

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM-Application-Manager#118]
I am frustrated by less everywhere if I don't want use it.
Better approach will be I think just mention about possible pager use, to end of info instead...

**Comment by ivan-hc** [comment]
I've wrote the option "test" for this. You can download the script with the option "-d" and drag/drop it in the terminal

**Comment by ivan-hc** [comment]
If you know a way to show all the outputs of the script in a way that every output can be replaced, please tell me

**Comment by ivan-hc** [comment]
@zen0bit this function must be updated, this should shof `less -E` during the installation but only for scripts that require interaction (for now just "libreoffice")
```
if grep -q "read -r -p " ./$arg; then
	$SUDOCOMMAND ./$arg | less -E
else
	$SUDOCOMMAND ./$arg
fi &&
```
all I want to do is to redirect each line of the script while running un the same line, and then it will be replaced.

All this only to leave a clean output.

Until now only using ` | less -E` allows what I want. Previously I had to use `xterm`, the latter was a dependency on AM/AppMan in the earlier versions.

If you know a better way to convert this nasty output...
```
-----------------------------------------------------------------------
 >> START OF ALL INSTALLATION PROCESSES <<
-----------------------------------------------------------------------

rm: impossibile rimuovere '/home/ivan/.local/share/applications/AM-ffwa-whatsapp.desktop': File o directory non esistente
/home/ivan/.cache/a 100%[===================>]   2,44K  --.-KB/s    in 0s      

 ◆ "FFWA-WHATSAPP" INSTALLED (1 MB OF DISK SPACE)                         

Anydesk-6.3.0-1-x86 100%[===================>]  13,86M  8,01MB/s    in 1,7s    

 ◆ "ANYDESK" INSTALLED (14 MB OF DISK SPACE)                              

-----------------------------------------------------------------------
 >> END OF ALL INSTALLATION PROCESSES <<
-----------------------------------------------------------------------
```
...with this...
```
-----------------------------------------------------------------------
 >> START OF ALL INSTALLATION PROCESSES <<
-----------------------------------------------------------------------

 ◆ "FFWA-WHATSAPP" INSTALLED (1 MB OF DISK SPACE)                         

 ◆ "ANYDESK" INSTALLED (14 MB OF DISK SPACE)                              

-----------------------------------------------------------------------
 >> END OF ALL INSTALLATION PROCESSES <<
-----------------------------------------------------------------------
```
please, tell me.

**Comment by ivan-hc** [comment]
@zen0bit in my tests I have replaced
```
$SUDOCOMMAND ./$arg | less -E
```
with
```
$SUDOCOMMAND ./$arg 2>&1 | grep -v ": "
```
I think that it is a good output... but its also too long!

Check it out (replace it in your script) and tell me if I can do something better than this.

**Comment by ivan-hc** [comment]
Check the new version, the installation process does not require "less"
