### ISSUE TITLE
there is no page ".about"

### ISSUE THREAD

**Issue by BarbzYHOOL** [ivan-hc/AM-Application-Manager#21]
this link in the readme is wrong

https://github.com/ivan-hc/AM-application-manager/tree/main/programs/.about

**Comment by ivan-hc** [comment]
Thank you, just corrected... this was a no longer available directory I had before switching everything to the new website, https://portable-linux-apps.github.io/

**Comment by BarbzYHOOL** [comment]
the links on that page are broken too!

**Comment by ivan-hc** [comment]
can you provide one?

**Comment by BarbzYHOOL** [comment]
[The app "Pippo" is not available in the database, how can I upload it?](https://portable-linux-apps.github.io/#the-app-pippo-is-not-available-in-the-database-how-can-i-upload-it)

**Comment by ivan-hc** [comment]
OK, everything works well now. Thank you for the feedback
