### ISSUE TITLE
add support for doas

### ISSUE THREAD

**Issue by FyrN22** [ivan-hc/AM-Application-Manager#22]
give a option to use doas instead of sudo

**Comment by ivan-hc** [comment]
can you provide more details?

**Comment by FyrN22** [comment]
duas is alternative to sudo, and you should give an option for using duas instead of sudo

**Comment by ivan-hc** [comment]
This is the first time I read about `doas` and I've not found many differences between it and `sudo`

Would you like to use a version of "AM" that does not require root privileges, instead? I suggest to use AppMan, it is "AM" that works locally (in your $HOME directory, or in a custom $HOME directory) no root privileges are needed, and you can place it wherever you want (I suggest in ~/.local/bin).

https://github.com/ivan-hc/AppMan

I can try a test for `doas`, but I hope you problem can be solved with AppMan, sincerelly. `sudo` is already a standard on may operating systems, not just GNU/Linux.

**Comment by FyrN22** [comment]
yeah i understand, i will try appman, nice project!

**Comment by FyrN22** [comment]
i attemped to make sudo file to /usr/bin and linked it to /usr/bin/doas, but i got now 
```
xterm: Xt error: Can't open display: %s
 ◆ "RPCS3" INSTALLED (1 MB OF DISK SPACE)"

``
i dont know if it becouse of doas or that im on wayland

**Comment by FyrN22** [comment]
i tired to make a file "/usr/bin/sudo" and linked it to "/usr/bin/duas" but i got the following errors `Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
 ◆ "RPCS3" INSTALLED (1 MB OF DISK SPACE)` but i dont know if the `xterm: Xt error: Can't open display: %s` error is becouse duas or wayland

**Comment by FyrN22** [comment]
the uninstall script worked with duas :)

**Comment by ivan-hc** [comment]
AppMan is done to work as a portable script and without root privileges. If you want you can setup a custom script into an USB stick with a custom $HOME directory, so you can use all the apps installed with AppMan wherever you want| ;)
