### ISSUE TITLE
Just installed and it doesn't work, no xterm

### ISSUE THREAD

**Issue by BarbzYHOOL** [ivan-hc/AM-Application-Manager#23]
> ERROR: "xterm" not found, required by some installation scripts.

ERROR: "zsync" not found, required by some installation scripts.

Install the above and try again

what are those???

**Comment by FyrN22** [comment]
install xterm and zsync

**Comment by ivan-hc** [comment]
zsync and xterm are dependences, the first one is used by some appimages with inbuilt instructions for the updates (about 6-7% of all Appimages) while xterm is needed to launch the installation script and to keep the main terminal clean when you install an application (in particular it is useful when you have to answer some prompts like in Firefox and Libreoffice).

**Comment by ivan-hc** [comment]
UPDATE: the new version 4.3.2 has not `xterm` between the dependencies, update now!

**Comment by BarbzYHOOL** [comment]
@ivan-hc it stills asks me for xterm, i have not uninstalled am but i pasted again `wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/INSTALL && chmod a+x ./INSTALL && sudo ./INSTALL`

**Comment by ivan-hc** [comment]
rm /opt/am/APP-MANAGER
    wget https://raw.githubusercontent.com/ivan-hc/AM-Application-Manager/main/APP-MANAGER -O /opt/am/APP-MANAGER
    chmod a+x /opt/am/APP-MANAGER

Try now
