### ISSUE TITLE
List and check requirements

### ISSUE THREAD

**Issue by www-wagner** [ivan-hc/AM-Application-Manager#26]
I think the `INSTALL` script should check if the required dependencies are satisfied before running. For example, I have a fresh Arch Linux new thin installation. I ran the AM installation script with no error or warning (instead, success message!) but it didn't work because I didn't have `wget` installed.

`APP-Manager` already has this check at the top of the script. But would be nice if all requirements were listed in README file to speed things up!

**Comment by ivan-hc** [comment]
OK, done for both, "AM" and Appman. Thank you.
