### ISSUE TITLE
Containerd

### ISSUE THREAD

**Issue by oenu** [ivan-hc/AM-Application-Manager#29]
Might be something obvious but im getting
```console
❯ am -f

find: ‘./containerd’: Permission denied
YOU HAVE INSTALLED 2 STANDALONE PROGRAMS MANAGED BY THE 'AM' COMMAND:

find: ‘./containerd’: Permission denied
find: ‘./containerd’: Permission denied
 ◆ am - 200KiB of disk space used
 ◆ obsidian - 100MiB of disk space used
```

```console
❯ am -u

 "AM" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS: 

find: ‘./containerd’: Permission denied
obsidian

 ALL OTHERS ARE FIXED VERSIONS OR CAN MANAGE UPDATES BY THEMSELF

 THE UPDATE VERIFICATION PROCESS IS IN PROGRESS, PLEASE WAIT...

-----------------------------------------------------------------------
 >> START OF ALL PROCESSES <<
-----------------------------------------------------------------------
 ◆ OBSIDIAN is updated, 1 seconds elapsed! 

-----------------------------------------------------------------------

 SYNCHRONIZING "AM" VERSION 4.3.2~1...

 THE "AM" SCRIPT IS NOW UPDATED TO THE 4.3.2~1 VERSION!  <<--GITHUB NOTE: This always appears

-----------------------------------------------------------------------
 >> END OF ALL PROCESSES << 
-----------------------------------------------------------------------

 ALL THE PROGRAMS MANAGED BY "AM" ARE UPDATED! 
```

and for completeness 
```console
❯ containerd --version
containerd containerd.io 1.6.21 3dce8eb055cbb6872793272b4f20ed16117344f8

```

Obsidian seems to be up to date with the most recent version, but im not sure why im getting the errors.

Thanks so much for all your work on this project! Appimages were kinda awful to deal with before your script! Grazie mille!

*Im considering making a frontend tool to hook into your repository if thats alright, let me know if you had plans to do the same*

**Comment by ivan-hc** [comment]
This same error appears in the video of DistroTube, "AM" expects you install it in /opt.

To use a portable version of "AM" use AppMan instead https://github.com/ivan-hc/AppMan

**Comment by ivan-hc** [comment]
You're right, AM is trying to read the content of a directory that normal users can't read

![Istantanea_2023-06-22_17-28-33](https://github.com/ivan-hc/AM-Application-Manager/assets/88724353/e013994c-0b2b-4770-98d9-c58e91e18816)

I've done a test by creating a directory in whitch I can't read normally

**Comment by ivan-hc** [comment]
> _Im considering making a frontend tool to hook into your repository if thats alright, let me know if you had plans to do the same_

This is what I hope to see soon https://github.com/ivan-hc/AM-Application-Manager/issues/8

I think a GUI with both "AM" an AppMan as an engine would be great!

If you need you can take a look also to the website https://portable-linux-apps.github.io

This may be also a part containing keywords in case you want to add a query, and in case you want to add links to the scripts I can convert the sorces of the "AM-installer" scripts from blob to raw, if you need it.

**Comment by oenu** [comment]
Fix worked, thanks for addressing!
