### ISSUE TITLE
Install AM in user-defined directory instead of /opt/

### ISSUE THREAD

**Issue by zenny** [ivan-hc/AM-application-manager#3]
@ivan-hc 

This looks pretty interesting.

Instead of forcing to install `am` and `am` installed programs under `/opt`, won't it be nice to echo a question during installation to a user-specified directory like `~/.local/opt` instead?

Just my two cents! Cheers.

**Comment by ivan-hc** [comment]
hi, it would be interesting to be able to offer the user the choice of the directory, were it not for the fact that we also have to modify the "launcher", the "remove" script and the link in $PATH. I have decided to [use the /opt folder for the purpose it is intended](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html) (LSB - Linux Standard Base).
Another advantage is that the applications (if installed at system level) are also available for other accounts (if there are multiple people using the same computer), and its this latter aspect which led me to write "AM".

PS: I have already created something that can install the programs locally, its name is "[AppMan](https://github.com/ivan-hc/AppMan)", but it was just my first experiment and it did not fully satisfy my concept of application manager. That's why I wrote "AM".

**Comment by zenny** [comment]
> hi, it would be interesting to be able to offer the user the choice of the directory, were it not for the fact that we also have to modify the "launcher", the "remove" script and the link in $PATH. I have decided to [use the /opt folder for the purpose it is intended](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html) (LSB - Linux Standard Base). Another advantage is that the applications (if installed at system level) are also available for other accounts (if there are multiple people using the same computer), and its this latter aspect which led me to write "AM".
> 
> PS: I have already created something that can install the programs locally, its name is "[AppMan](https://github.com/ivan-hc/AppMan)", but it was just my first experiment and it did not fully satisfy my concept of application manager. That's why I wrote "AM".

Yep I read your intention about creating this and do fully agree. Yet `/opt` is the location where other locally-compiled application already resides and may create a conflict. If you want to make the application available at system level, I suggest you to move the AM applications to install not directly to `/opt` folder, but either inside `/opt/am` or /`opt/AM`. Just my two cents. Cheers,

**Comment by ivan-hc** [comment]
thank you for your interest, but I repeat that the apps are installed in /opt just as the LSB wants. For example, the Firefox installation scripts place the application just [as suggested in the Debian wiki](https://wiki.debian.org/Firefox#From_Mozilla_binaries), while Google Chrome is installed right in / opt (and only in /opt), [as it is already structured in the .deb package it is taken from](https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable). So the choice is certainly not mine and mine alone, but LSB's. 

The only thing you could dispute is the choice of launchers in /usr/share/applications, while for binaries I preferred to force links in /usr/local/bin. These may overwrite existing installations of the same software, so [I have already warned users of this problem](https://github.com/ivan-hc/AM-application-manager#important), by advising them to choose only one version of the same software, either from "AM" or their package manager, but NEVER TOGETHER.

Finally, my goal is to provide official software from the original developer sites and / or repositories, so brave (for now AppImage), gimp, vlc, inkscape, chromium / chromium ungoogled (for now from Slackware), Vivaldi Stable ( for now from Arch Linux) are just some of the interim scripts that need to be rewritten, and that's my priority right now. Placing all these external and (in fact) "optional" (hence the name of the directory /opt) programs in that specific folder is certainly the right choice that someone could make for a third party package manager, without therefore having to add additional folders to the root, ie "/" ( unlike snappy, flatpak and the GNU/Linux distribution Nitrux, with its /Applications folder).

**Comment by ivan-hc** [comment]
@zenny I have just finished to improve AppMan using the last release of "AM" as code base, here is the link to the repository:

https://github.com/ivan-hc/AppMan

everything works locally, with all the features and advantages of "AM" 2.6.1-2. I hope you enjoy it.
