### ISSUE TITLE
BUILD file format 

### ISSUE THREAD

**Issue by DLopezJr** [ivan-hc/AM-Application-Manager#31]
I am still not fully familiar with building appimages, but I see potential for a BUILD file format. 

Most maintainers of packages are familiar with the BUILD format files from most big distros. This may lead to attracting maintainers with an easy file format.

Will start sketching some ideas out this week and place them in here.

Resources:
https://wiki.gentoo.org/wiki/Ebuild
https://wiki.alpinelinux.org/wiki/APKBUILD_Reference
https://wiki.archlinux.org/title/PKGBUILD
https://github.com/void-linux/void-packages/blob/master/Manual.md

**Comment by ivan-hc** [comment]
Sorry for my ignorance, but why?

Are my templates too complicated if compared with a PKGBUILD?

**Comment by DLopezJr** [comment]
No worries at all. I was brief due to time constraint.

I've been browsing over the codebase and looking for places to make optimize. 

A file format might be useful in standardizing the process and providing variables and functions that the package manager can take advantage of. Take some time to get familiar with the ones I posted. When I have more time I will post some specific ideas.

**Comment by ivan-hc** [comment]
Let me know what you have in mind, I need to understand what is not good in my scripts.
