### ISSUE TITLE
Request to include a program

### ISSUE THREAD

**Issue by shreyasastech** [ivan-hc/AM-Application-Manager#39]
It would be nice if you could include this text editor named [**lite-xl**](https://github.com/lite-xl/lite-xl/) to the Application Manager. It's a neat little text editor with very good syntax highlighting and it is very light-weight as well. Normal & Addons AppImages are found in [releases](https://github.com/lite-xl/lite-xl/releases/latest/).

Addons AppImage is actually lite-xl + addons and not just the addon packages hence it would be very nice to include both AppImages as two programs.

**Comment by ivan-hc** [comment]
in both cases they don't seem too big to me, I'll upload it shortly. Thanks for the tip, I'll upload the one with addons.

**Comment by ivan-hc** [comment]
Solved https://github.com/ivan-hc/AM-Application-Manager/commit/7da3366193da467c72aab903f281be9c8e3a726e

**Comment by shreyasastech** [comment]
Thanks for the quick response and adding Addons package. Now I would be able to install and update it pretty easily through AM. Keep up the good work, brother. ❤️
