### ISSUE TITLE
AM as the AppImage package managers of Apx, the default package manager in Vanilla OS

### ISSUE THREAD

**Issue by Thatoo** [ivan-hc/AM-Application-Manager#42]
Do you know Apx, https://github.com/Vanilla-OS/apx , the default package manager in Vanilla OS. It is a wrapper around multiple package managers to install packages and run commands inside a managed container.

It would be nice that Apx use AM or AppMan to handle AppImages : https://github.com/Vanilla-OS/apx/issues/227

**Comment by ivan-hc** [comment]
That would be nice, you can suggest it to whoever you want :) Thank you!
