### ISSUE TITLE
Logseq install correctly but don't open

### ISSUE THREAD

**Issue by www-wagner** [ivan-hc/AM-Application-Manager#43]
Using AM 4.3.2~5.1 on Arch Linux KDE.

Logseq app has been installed but it's not opening.

The `AM-logseq.desktop` file seems to be the problem because `Exec` command is in capitalcase as `/opt/logseq/logseq` is in lowercase.

```
[Desktop Entry]
Categories=Utility
Comment=A privacy-first, open-source platform for knowledge management and collaboration.
Comment=A privacy-first, open-source platform for knowledge management and collaboration.
Exec=Logseq %u
GenericName=
GenericName=
Icon=/opt/logseq/icons/logseq
MimeType=
Name=Logseq
Name=Logseq
Path=
StartupNotify=true
StartupWMClass=Logseq
Terminal=false
TerminalOptions=
Type=Application
X-AppImage-Version=0.9.10
X-KDE-SubstituteUID=false
X-KDE-Username=
```

The icon hasn't shown as well because the `/opt/logseq/icons/logseq` is a symlink that points to a unknown file `usr/share/icons/hicolor/256x256/apps/Logseq.png`.

**Comment by ivan-hc** [comment]
Solved! https://github.com/ivan-hc/AM-Application-Manager/commit/927ea6be2853f06cab406f9f21e330b9584ba3f5
