### ISSUE TITLE
usage of creating appimage ?

### ISSUE THREAD

**Issue by docop** [ivan-hc/AM-application-manager#5]
Hi   i just want to know can it be used to convert an app that is running / installing from those snap package ? In order to like.. install from that snap stuff and then convert in appimage to have it usable.
Thanks

**Comment by ivan-hc** [comment]
it is totally possible, I've already tried to convert a Snap into an AppImage and it worked well with the correct AppRun. Snap and AppImage packages can also be renamed as ZIP files and extracted with a tool line Engranpa, if you want to check them. I'm planning to use also programs packaged as snap to convert them into AppImages, the structure is not much different.

**Comment by docop** [comment]
Wow, that can be very very nice. an app that convert directly to appimage. pretty cool function. i will follow for sure.
Happy new year.
