### ISSUE TITLE
missing liberary in appimage apps

### ISSUE THREAD

**Issue by maheshp1999** [ivan-hc/AM-Application-Manager#50]
I downloaded app from portable linux app, KDEgames-suite-22.12.3-1-x86_64.AppImage.  Try to open it after providing execution permission on ubuntu but it didnot open.

When tried opening it through terminal got the message of missing liberary GLIBC_2.33 not found. Please check why dependancy should be missing.
![Screenshot from 2023-07-22 20-32-16](https://github.com/ivan-hc/AM-Application-Manager/assets/140376451/4db33e12-7fff-47e6-b03e-3666d1a4e377)

**Comment by ivan-hc** [comment]
This means that your system is too old to use this Appimage.

My AppImage is built on top of Debian Stable (GLIBC 2.36+), while your ZorinOS uses an old GLIBC (maybe it is based on Ubuntu 18.04 or 20.04... I don't know what version uses your ZorinOS installation).

So the message says that you should upgrade to use newer GLIB versions. **At least GLIBC 2.34**

This is a table that reports GLIBC versions copmpatibility/availability: https://repology.org/project/glibc/versions

Newer GLIBC versions on the host can execute all older AppImages.

NOTE: don't upgrade GLIBC only on your system, it is a core dependenci of all the system and may break everything. The safest way is to upgrate to the next version.

**Comment by ivan-hc** [comment]
If you're interested in something newer that works quite well, try this script I wrote just today:

https://github.com/ivan-hc/KDE-games-suite-appimage/blob/main/kde-games-junest.sh

To learn more about it, visit https://github.com/ivan-hc/ArchImage , ArchImages are something that works on systems older than yours. Uses a containerized Arch Linux distro as base, so the games are newer than those included in my Appimage.

See the video on the repo, then read and learn exactly what the script does. The only issue you can face is that the script would not recognize your locale, in that case, comment (put # at he begin of) the lines fro 30 to 32 and try again.

Execute the script into a new directory, the final Appimage is about 330 MB.

Have fun!

**Comment by maheshp1999** [comment]
sorry to bother you but i tried the same file to be run on ubuntu 22.04lts version where glibc 2.35 is available still file does not open. in terminal it only list the games available but does not start.

**Comment by ivan-hc** [comment]
> glibc 2.35

OK, this means that the Appimage only works with distros with GLIBC 2.36+

As I've already said, this Appimage is based on Debian 12 Stable

**Comment by ivan-hc** [comment]
UPDATE: try now https://github.com/ivan-hc/KDE-games-suite-appimage/releases/tag/continuous now I use ArchImage as base

**Comment by maheshp1999** [comment]
thanks Ivan for all your efforts.
I am not highly tech savvy to build etc. 

My though was that all appimage can run on any OS and any version so i was trying it.
Appreciate your support.
