### ISSUE TITLE
Adding quarto-cli to the app list

### ISSUE THREAD

**Issue by Martin15135215** [ivan-hc/AM-Application-Manager#52]
quarto-cli has a github repo: https://github.com/quarto-dev/quarto-cli

https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.433/quarto-1.3.433-linux-amd64.tar.gz

Thanks for the effort

**Comment by ivan-hc** [comment]
Done https://github.com/ivan-hc/AM-Application-Manager/commit/82cad737fd2fbb3b48e4e16c006a900983e79b55 https://github.com/ivan-hc/AM-Application-Manager/commit/984c9f7db6a00bcb19afe193bfaeaf01e3a872f5
