### ISSUE TITLE
inkscape-next not working for both am and appman

### ISSUE THREAD

**Issue by gorimakpa** [ivan-hc/AM-Application-Manager#54]
The installation script for inkscape-next in both am and appman are not working. Once the installs are done, the programs don't launch.

**Comment by ivan-hc** [comment]
This is because they have changed the websit... I'll try to fix this issue

**Comment by ivan-hc** [comment]
Luckly the download pages are still the same, all changes is the way  the tag is shown on that page.

I can get this from gitlab, anyway. This is not a problem for the last release... but it is a problem for the development release.

I can fix the issue for inkscape stable, not for inkscape-next, or at least not for now.

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM-Application-Manager/commit/228c9fe0179f964117adeb6eb654b79602e4e5b9 should fix inkscape stable... but they have a system to hide tags very impressive. I have difficults to find right solution.

**Comment by gorimakpa** [comment]
No worries! Thanks again.

**Comment by ivan-hc** [comment]
wait, I've not finished... for now I've found an alternative solution to download the last version

version=$(echo https://inkscape.org/$(wget -q https://inkscape.org/release/all/gnulinux/appimage/ -O - | grep "gallery/item" | tail -1 | grep -o -P '(?<=href="/).*(?=">)'))
wget $version

however, now both the stable and the next release are the same thing... I need to correct this

**Comment by ivan-hc** [comment]
OK, I've found a solution

Stable

    tag=$(wget -q https://inkscape.org/release/all/gnulinux/appimage/ -O - | grep -i "release/inkscape" | grep -v rc | grep -v beta | grep -v alpha | tail -1 | grep -o -P '(?<=ape ).*(?=</a>)')
Next

    tag=$(wget -q https://inkscape.org/release/all/gnulinux/appimage/ -O - | grep -i "release/inkscape" | tail -1 | grep -o -P '(?<=ape ).*(?=</a>)')
