### ISSUE TITLE
[BUG] Application Icons dont use icon theme

### ISSUE THREAD

**Issue by Cyanide-1** [ivan-hc/AM-Application-Manager#57]
Essentially, for every appimage i download, it doesnt use the icon theme i am currently using, im currently using Papirus icon theme and normally when i install apps, it uses this icon theme, i have installed ventoy from the AUR (i am using arch linux) and ventoy from the AUR works with my icon theme, but ventoy from AM doesnt show the correct icon, this happens with every single app from AM and not just ventoy, i consider this a bug and its not an issue with Papirus icon theme, i ask that this please get fixed, thank you

**Comment by ivan-hc** [comment]
The path each app installed via AM is `/opt/$APP/icons`, so this is not a path recognized by the Linux standards (normally `/usr/share/icons` or `/usr/share/pixmaps`).

To fix this you should copy the launcher of each app to your $HOME/.local/share/applications (if it does not exists, just create it), then use your text editor and change the `Icon=/opt/$APP/icons/$APP` entry to  `Icon=$APP` or the name of the icon you want to see.

If you install `menulibre` you can change the icons and edit the launchers on the application's menu easily.

AM aims to use only original parts from each application it manages.

**Comment by Cyanide-1** [comment]
alright, thanks for the response
