### ISSUE TITLE
The tor-browser download page has changed.

### ISSUE THREAD

**Issue by tuchanemo** [ivan-hc/AM-Application-Manager#63]
Hi, the download page of https://www.torproject.org/download/languages/ has changed. Please correct the installation script.

**Comment by ivan-hc** [comment]
Fixed, and also added more info on how the script works (this was one of my really first scripts, before I create standard templates for my installation scripts).

I've also changed the command to download the last version of Tor Browser from the download page:

```
wget https://www.torproject.org/$(wget -q https://www.torproject.org/download/ -O - | grep -i linux | grep 'tar.xz"' | sed 's/ //g' | head -1 | grep -o -P '(?<="href=").*(?=">)')
```
Now the installation script looks better.

Thank you for the feedback.
