### ISSUE TITLE
am command errors

### ISSUE THREAD

**Issue by Prisoner709** [ivan-hc/AM-Application-Manager#64]
Ciao Ivan, from today, any am command returns me this error: 
ERROR: ar not found, required by some installation scripts.
Install the above and try again
You know why? I tried to reinstall but without success. I'm on Fedora 38.
Grazie.

**Comment by ivan-hc** [comment]
Hi, the command `ar` is needed to unpack the .deb packages, normally it is provided with the "binutils" package.

Since about one year, AM check the following commands in $PATH:

"ar" "cat" "chmod" "chown" "curl" "grep" "sed" "tar" "unzip" "wget" "zsync"

**Comment by ivan-hc** [comment]
Actually the only installation scripts that use the "ar" command are windows95 (for x86_64) and some scripts for i686 and (maybe) ARM (I don't remember), but "binutils" is normally installed by default in all GNU/Linux distributions.

**Comment by Prisoner709** [comment]
Ok..., binutils solved the problem. Grazie. 
P.S. Seven O Nine.... exactly.
