### ISSUE TITLE
Can't install viber.

### ISSUE THREAD

**Issue by tuchanemo** [ivan-hc/AM-Application-Manager#66]
Hi, when I try to install viber, wget gives a message: missing URL.
On the page https://aur.archlinux.org/packages/viber the link to the sources has changed.
Now the link points to the deb package.
Please correct the installation script. Thanks.

**Comment by ivan-hc** [comment]
Seems that these scripts pointing to AUR are a pain in the ass sometime, however they are useful to track the version's number if the main site does not provides it.

When the number will change, also the AM-updater will perform a download using wget, like this:
```
wget https://download.cdn.viber.com/desktop/Linux/viber.AppImage -O $APP
```
if you have problems now and the AppImage is not in place, remove or edit /opt/viber/version and run the command `am -u` or `am -u viber`

You can see the changes at commit https://github.com/ivan-hc/AM-Application-Manager/commit/0a59861216e87572926bc293dd50c4273f5960b3

**Comment by tuchanemo** [comment]
Thanks for the correction, but there is a nuance.
After installation, in the file am-viber.desktop the Exec line contains the name of Viber program with a capital letter, but the name of the executable file /usr/local/bin/viber starts with a small letter. Therefore, the system does not find the Viber file at startup.

**Comment by ivan-hc** [comment]
This commit should fix the issue https://github.com/ivan-hc/AM-Application-Manager/commit/527d86ee5e13703d392f0ef7b4f636c7e778d637

Just tested on my PC.
