### ISSUE TITLE
Add Jetbrains Toolbox to supported Apps

### ISSUE THREAD

**Issue by 3nigm4** [ivan-hc/AM-Application-Manager#75]
Could you add Jetbrains Toolbox as a supported app?

https://www.jetbrains.com/toolbox-app/

If you click on System Reqirements it states:
Linux: 64-bit x86, glibc 2.17 (Ubuntu 18.04 or newer). Toolbox App is packaged in [AppImage](http://appimage.org/) and requires FUSE to run. See [AppImage Wiki](https://github.com/probonopd/AppImageKit/wiki/FUSE) for details.
The following packages must be present:
libfuse2 libxi6 libxrender1 libxtst6 mesa-utils libfontconfig libgtk-3-bin tar

**Comment by ivan-hc** [comment]
Done https://github.com/ivan-hc/AM-Application-Manager/commit/eff6587bc6080595714bf3c5f07f08453ceab06b

I don't want to doubt the security of this app, but personally I don't like applications that do what they want on their own and without authorization.

Learn more in the notes of this commit.

**Comment by 3nigm4** [comment]
Thank you so much! Me neither, but what can you do, when you have to use the software...
