### ISSUE TITLE
Would it be possible to add RStudio IDE?

### ISSUE THREAD

**Issue by Martin15135215** [ivan-hc/AM-Application-Manager#78]
Here is the GitHub repo: https://github.com/rstudio/rstudio

Even so, there are no builds.

At this website, there are links to the builds: https://posit.co/download/rstudio-desktop/

Nevertheless, I am not sure how easy it is to get those builds in a bash script from that website.

If that is too difficult, I will just download the deb package myself as usual.

**Comment by ivan-hc** [comment]
it would be easy to manage the tar.gz archive... but I'm trying to test it and I get these errors:
```
[3822:1012/141111.668001:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[3822:1012/141111.670967:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```
I have also tried the version in the .deb package and I get the same errors.

I can see that this is an electron-based app (based on Chromium/Google Chrome).

**Comment by ivan-hc** [comment]
The official TAR for Ubuntu Focal is uploaded https://github.com/ivan-hc/AM-Application-Manager/commit/d28b3b14ddef746799a75710023237479fb43fad

I can't solve the issue above, maybe I have some missing dependence on my system.

This is the control file in the DEB package:
```
Architecture: amd64
Depends: libssl1.0.0 | libssl1.0.2 | libssl1.1, libclang-dev, libxkbcommon-x11-0, libsqlite3-0, libpq5,  libc6 (>= 2.7)
Description: RStudio
 RStudio is an integrated development environment (IDE) designed to support multiple languages, including both R and Python. It includes a console, syntax-highlighting editor that supports direct code execution, and a variety of robust tools for plotting, viewing history, debugging and managing your workspace.
Maintainer: RStudio <info@posit.co>
Package: rstudio
Priority: optional
Section: devel
Suggests: r-base (>= 3.3.0)
Version: 2023.09.0+463
Installed-Size: 650823
```
maybe I miss a dependence on my system.

**Comment by Martin15135215** [comment]
Hi, i had the same problem on my debian-based system. I coulnd't run RStudio without installing fisrt `r-base`. It's really bizzare, because it say's also in your control file, that `r-base` is only under _Suggensts_ instead of _Depends_

So first do `sudo apt install r-base` and then install RStudio

**Comment by ivan-hc** [comment]
OK, if this works for you then I can just specify on the dedicated page of the website:

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/blob/main/apps/rstudio.md

**Comment by Martin15135215** [comment]
The R package is only called in debian-based system `r-base`

For Fedora, for example, it is called simply `R`

See this site for more information https://cran.rstudio.com/ or https://www.r-project.org/

**Comment by ivan-hc** [comment]
OK, just updated the page. Anyone can consult this info via the `-a` option.
