### ISSUE TITLE
am installs pre-release instead of latest of quarto-cli from github repo

### ISSUE THREAD

**Issue by Martin15135215** [ivan-hc/AM-Application-Manager#79]
https://github.com/quarto-dev/quarto-cli/releases

This is latest: https://github.com/quarto-dev/quarto-cli/releases/latest

**Comment by ivan-hc** [comment]
Done https://github.com/ivan-hc/AM-Application-Manager/commit/633092c1f5220d879cf93d951494b0b6d61238fd

Thank you.

**Comment by Martin15135215** [comment]
Also a question, the executable of the quarto-cli github repo is named quarto -> can the symlink under /usr/local/bin also be named quarto instead of quarto-cli?

**Comment by ivan-hc** [comment]
> Also a question, the executable of the quarto-cli github repo is named quarto -> can the symlink under /usr/local/bin also be named quarto instead of quarto-cli?
> 
> Because other program that rely on quarto can not find quarto

Here you are https://github.com/ivan-hc/AM-Application-Manager/commit/ed69ce20d7fb5e3409aa3f99c2109e51351340d3

**Comment by Martin15135215** [comment]
Thanks! I can confirm, that zettlr does find quarto. BTW, Both software installed with am !

![image](https://github.com/ivan-hc/AM-Application-Manager/assets/110968398/329ae74d-323c-4060-b167-545bd3d9ef7a)
