### ISSUE TITLE
Zoom fails to start from App Menu

### ISSUE THREAD

**Issue by msz59** [ivan-hc/AM-Application-Manager#85]
Installing 'zoom' with AM places /usr/share/applications/AM-zoom.desktop file containing
`Exec=ZoomLauncher %U`
line but there is no `ZoomLauncher` anywhere. In /usr/local/bin there is just a plain `zoom`, linked to `/opt/zoom/`
Surely enough, trying to run Zoom from the Applications->Internet menu fails.
It is on Void Linux, XFCE, but I guess the distribution is irrelevant here.

Anyway, big thanks for AM, it is of great help especially on such a Linux as Void which does not use DEBs or RPMs.

regards, Michal

**Comment by ivan-hc** [comment]
Try now

**Comment by msz59** [comment]
It works now as expected, thanks.
FYI, I had to remove and install. 'Update' option apparently did nothing, responding immediately with
`ZOOM is updated, 0 seconds elapsed! `
But maybe I misunderstand the meaning of that option.

**Comment by ivan-hc** [comment]
Wait until the next release will be available... or try to edit/change the line in the file /opt/zoom/version, save and perform the update... just for test porpouse, and you will see ;)

**Comment by ivan-hc** [comment]
Look, this way

https://github.com/ivan-hc/AM-Application-Manager/assets/88724353/52943a1a-c932-4472-b2d0-3b493a920f01

AM compares the new version from the repository with the installed one (read the file /opt/zoom/AM-updater), this is how almost all apps managed by AM can be updated.
