### ISSUE TITLE
How do I switch from `/usr'share` to `/usr/local/share`?

### ISSUE THREAD

**Issue by dnkmmr69420** [ivan-hc/AM-Application-Manager#86]
IDK how to do it

**Comment by ivan-hc** [comment]
In first, you should create a directory "applications" there:
```
sudo mkdir -p /usr/local/share/applications
````
Then you shoud edit the file /opt/am/APP-MANAGER. Add the following line after the 598 one:
```
sed -i "s#/usr/share/applications#/usr/local/share/applications#g" ./$arg
```
original lines are these:
```
										chmod a+x ./$arg
										sed -i "s#wget #wget -q --show-progress #g" ./$arg
```
they should look like this:
```
										chmod a+x ./$arg
										sed -i "s#/usr/share/applications#/usr/local/share/applications#g" ./$arg
										sed -i "s#wget #wget -q --show-progress #g" ./$arg
```
do this every time you update with options `-u` and `-s`.

## How to prevent AM updating itself
This step is needed to keep your custom /opt/am/APP-MANAGER file without updating it:
- find and remove `$AMCLIPATH -s` from the file (originally it is the line 1530, if you add the line above it become 1531), this will prevent `-u` of using the option `-s` to update the /opt/am/APP-MANAGER script;
- in addition, remove the optino `-s` completelly, these lines:
```
  '-s'|'sync')
    	if [ -n "$SUDO_COMMAND" ]; then 
		echo -e "\n WARNING: You don't need to run the option '$1' with SUDO.\n"; 
		exit; 
	fi
	
  	rm -R -f $AMPATH/$arch-apps $AMPATH/list && wget -q $AMREPO/programs/$arch-apps -P $AMPATH && echo -e "$(cat $AMPATH/$arch-apps | awk -v FS="(◆ | : )" '{print $2}')" >> $AMPATH/list
	cd $AMPATH && cat options >> list
	echo ""; echo ' SYNCHRONIZING "'$(echo $AMCLI | tr a-z A-Z)'" VERSION '$($AMCLIPATH -v)'...'; sleep 0.5; echo "";
  	rm -R -f $AMPATH/.cache/* 1>/dev/null; cd $AMPATH/.cache; wget -q $AMREPO/APP-MANAGER && chmod a+x ./APP-MANAGER; cd ..;
  	mv $AMPATH/.cache/APP-MANAGER $AMPATH; chmod 777 $AMPATH; echo ' THE "'$(echo $AMCLI | tr a-z A-Z)'" SCRIPT IS NOW UPDATED TO THE '$($AMCLIPATH -v)' VERSION! '; echo ""
	;;
```

Now you have an "immutable" version of "AM" (immutable in the sense that new features will not be added anymore... at least until you download it again manually).

Remember to follow me on github or watch all updates of "AM" to see new features available.

For now I lack of fantasy, so you're safe.

**Comment by ivan-hc** [comment]
I've solved with this commit https://github.com/ivan-hc/AM-Application-Manager/commit/f758f5e1848e5d9ddaa0b307fe40cc40d0046c6e update to AM 5.1
