### ISSUE TITLE
ficus package is missing ficus binary

### ISSUE THREAD

**Issue by step-** [ivan-hc/AM-Application-Manager#88]
Hello, thank you for MA-Application-Manager!
I need to report that the ficus package installs /usr/local/bin/ficus as a broken link to /opt/ficus/ficus, which is missing.
Is it OK to report issues like this - relating to non-working individual packages - in this repo, or do you prefer some other way?

**Comment by ivan-hc** [comment]
You have done well, as reported at https://github.com/ivan-hc/AM-Application-Manager#wrong-download-link

Thank you

**Comment by step-** [comment]
Your response time was phenomenal! Now ficus downloads and runs.
Thank you.

**Comment by ivan-hc** [comment]
> Your response time was phenomenal

it was just a coincidence that I turned on the PC at the moment you contacted me, hahaha xD

**Comment by step-** [comment]
Well, OK. But the commit doesn't look exactly trivial to me. You had to change several lines in a very short time. Anyway, thank you again.

**Comment by ivan-hc** [comment]
Just `am -t ficus`, then tested the script on my PC, noted that the icon was missing, so I've added the related icon's path in the script (ie /usr/share/icons/hicolor/0x0/apps/). Done. My templates are my plan B and are life saver.

**Comment by step-** [comment]
Cool
