### ISSUE TITLE
Some software for our list

### ISSUE THREAD

**Issue by Drsheppard01** [ivan-hc/AM-Application-Manager#9]
acreom https://github.com/Acreom/releases/releases/download/v0.8.9/acreom-0.8.9.AppImage
allusion https://github.com/allusion-app/Allusion/releases/download/v1.0.0-rc8.1/Allusion-1.0.0-rc8.1.AppImage
boostnote https://github.com/BoostIO/BoostNote-App/releases/latest/download/boost-note-linux.AppImage
cerebro https://github.com/cerebroapp/cerebro/releases/download/v0.8.0/Cerebro-0.8.0.AppImage
cherrytree https://www.giuspen.net/software/CherryTree-0.99.50-x86_64.AppImage
cider https://github.com/ciderapp/cider-releases/releases/download/v1.5.7/Cider-1.5.7.AppImage
cinelerra-gg https://cinelerra-gg.org/download/images/CinGG-20220928-x86_64.AppImage
cinny https://github.com/cinnyapp/cinny-desktop/releases/download/latest/Cinny_desktop-x86_64.AppImage
conduction https://github.com/Shabang-Systems/Condution/releases/download/v1.1.1/Condution-1.1.1.AppImage
contour https://github.com/contour-terminal/contour/releases/download/v0.3.4.223/contour-0.3.4.223_x86_64.AppImage
coolero https://gitlab.com/coolero/coolero
czkawka https://github.com/qarmin/czkawka/releases/download/5.0.2/linux_czkawka_gui.AppImage
ente https://github.com/ente-io/bhari-frame/releases/download/v1.6.10/ente-1.6.10.AppImage
extraterm https://github.com/sedwards2009/extraterm/releases/download/v0.66.0/ExtratermQt-0.66.0.glibc2.25-x86_64.AppImage
ferdium https://github.com/ferdium/ferdium-app/releases/download/v6.2.0/Ferdium-linux-Portable-6.2.0-x86_64.AppImage
filen https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
geeqie https://cclark.uk/Geeqie/Geeqie-v2.0+20220921.AppImage
gridplayer https://github.com/vzhd1701/gridplayer/releases/download/v0.4.3/GridPlayer-0.4.3-x86_64.AppImage
heroic https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.4.3/Heroic-2.4.3.AppImage
hypertrader https://download.hypertrader.app/HyperTrader-2.27.2.AppImage
inochi-creator https://github.com/Inochi2D/inochi-creator/releases/download/v0.7.3/inochi-creator-x86_64.AppImage
joplin https://github.com/laurent22/joplin/releases/download/v2.8.8/Joplin-2.8.8.AppImage
kuro https://github.com/davidsmorais/kuro/releases/download/v8.1.5/Kuro-8.1.5.AppImage
laidout https://github.com/Laidout/laidout/releases/download/continuous/Laidout-ae6b35e-x86_64.AppImage
librecad https://github.com/LibreCAD/LibreCAD/releases/download/latest/LibreCAD-2.2.0-rc4-17-g07ef2b45-x86_64.AppImage
logseq https://github.com/logseq/logseq/releases/download/0.8.8/Logseq-linux-x64-0.8.8.AppImage
mendeley https://static.mendeley.com/bin/desktop/mendeley-reference-manager-2.77.0-x86_64.AppImage
midterm https://midterm.app/download/download-linux
moosync https://github.com/Moosync/Moosync/releases/download/v5.1.0/Moosync-5.1.0-linux-x86_64.AppImage
neovim https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
netbeans https://github.com/codelerity/netbeans-installers/releases/download/v15-build1/Apache_NetBeans-15-x86_64.AppImage
notes https://github.com/nuttyartist/notes/releases/latest/download/Notes-x86_64.appimage
nuclear https://github.com/nukeop/nuclear/releases/download/9545bf/nuclear-9545bf.AppImage
openComic https://github.com/ollm/OpenComic/releases/download/v0.2.1/OpenComic-0.2.1.AppImage
Pencil2d https://github.com/pencil2d/pencil/releases/download/v0.6.6/pencil2d-linux-amd64-0.6.6.AppImage
picoctypt https://github.com/HACKERALERT/Picocrypt/releases/download/latest/Picocrypt.AppImage
pocket-browser https://github.com/PocketStudios/Pocket-Browser/releases/download/v1.7.0/pocket-browser-1.7.0.AppImage
quaternion https://github.com/quotient-im/Quaternion/releases/download/0.0.95.1/quaternion-0.0.95.1.AppImage
qview https://github.com/jurplel/qView/releases/download/5.0/qView-5.0-x86_64.AppImage
revolt https://github.com/revoltchat/desktop/releases/download/v1.0.6/Revolt-1.0.6.AppImage
ricochet https://github.com/blueprint-freespeech/ricochet-refresh/releases/download/v3.0.14-release/Ricochet_Refresh-28bd7c0-x86_64.AppImage
sfbrename https://github.com/karwler/sfbrename/releases/download/v1.0.0/sfbrename-gtk-1.0.0-x86_64.AppImage
session-desktop https://github.com/oxen-io/session-desktop/releases/download/v1.10.1/session-desktop-linux-x86_64-1.10.1.AppImage
simplenote https://github.com/Automattic/simplenote-electron/releases/download/v2.21.0/Simplenote-linux-2.21.0-x86_64.AppImage
skrooge https://download.kde.org/unstable/skrooge/skrooge-2.28.0-x86_64.AppImage
sleek https://github.com/ransome1/sleek/releases/download/v1.2.2/sleek-1.2.2.AppImage
sonixd https://github.com/jeffvli/sonixd/releases/download/v0.15.3/Sonixd-0.15.3-linux-x86_64.AppImage
speek https://github.com/Speek-App/Speek/releases/download/v1.7.0-release/Speek.Chat-1.7.0-linux-x86_64.AppImage
sunamu https://github.com/NyaomiDEV/Sunamu/releases/download/v2.1.0/Sunamu-2.1.0.AppImage
szyzka https://github.com/qarmin/szyszka/releases/latest/download/linux_szyszka.AppImage
theia-blueprint https://www.eclipse.org/downloads/download.php?file=/theia/latest/linux/TheiaBlueprint.AppImage
twake https://github.com/linagora/Twake-Desktop/releases/latest/download/Setup_Twake_lastest.AppImage
unityhub https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
viber https://download.cdn.viber.com/desktop/Linux/viber.AppImage
vikunja https://dl.vikunja.io/desktop/0.19.1/Vikunja%20Desktop-0.19.1.AppImage
webcord https://github.com/SpacingBat3/WebCord/releases/download/v3.8.6/WebCord-3.8.6-x64.AppImage
zrythm https://www.zrythm.org/downloads/zrythm-trial-1.0.0.beta.3.5.1-x86_64.AppImage

**Comment by ivan-hc** [comment]
I'm back again, I've not uploaded yet the following apps:

- cherrytree https://www.giuspen.net/software/CherryTree-0.99.50-x86_64.AppImage
- cinelerra-gg https://cinelerra-gg.org/download/images/CinGG-20220928-x86_64.AppImage
- coolero https://gitlab.com/coolero/coolero
- filen https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
- geeqie https://cclark.uk/Geeqie/Geeqie-v2.0+20220921.AppImage
- hypertrader https://download.hypertrader.app/HyperTrader-2.27.2.AppImage
- mendeley https://static.mendeley.com/bin/desktop/mendeley-reference-manager-2.77.0-x86_64.AppImage
- midterm https://midterm.app/download/download-linux
- skrooge https://download.kde.org/unstable/skrooge/skrooge-2.28.0-x86_64.AppImage
- theia-blueprint https://www.eclipse.org/downloads/download.php?file=/theia/latest/linux/TheiaBlueprint.AppImage
- unityhub https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
- viber https://download.cdn.viber.com/desktop/Linux/viber.AppImage
- vikunja https://dl.vikunja.io/desktop/0.19.1/Vikunja%20Desktop-0.19.1.AppImage
- zrythm https://www.zrythm.org/downloads/zrythm-trial-1.0.0.beta.3.5.1-x86_64.AppImage

It would be helpful if for each of these you can provide:

- a link (or better a `curl` or `wget` command) that always redirects to the last version available (without having to speciphy the number of the version);
- a command to check the last available version (this is needed for the script named "AM-updater" that updates each program to the latest version).

I can try to obtain the icon and the launcher directly from the AppImage itself (using the `./*AppImage --appimage-extract`) command, but if there is already a source where we can download them directly (and without having to extract everything every time) it would be great!

**Comment by ivan-hc** [comment]
Apps left:

- hypertrader https://download.hypertrader.app/HyperTrader-2.27.2.AppImage
- mendeley https://static.mendeley.com/bin/desktop/mendeley-reference-manager-2.77.0-x86_64.AppImage
- midterm https://midterm.app/download/download-linux
- skrooge https://download.kde.org/unstable/skrooge/skrooge-2.28.0-x86_64.AppImage
- theia-blueprint https://www.eclipse.org/downloads/download.php?file=/theia/latest/linux/TheiaBlueprint.AppImage
- unityhub https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
- viber https://download.cdn.viber.com/desktop/Linux/viber.AppImage
- vikunja https://dl.vikunja.io/desktop/0.19.1/Vikunja%20Desktop-0.19.1.AppImage
- zrythm https://www.zrythm.org/downloads/zrythm-trial-1.0.0.beta.3.5.1-x86_64.AppImage

Just created and uploaded cherrytree, cinelerra-gg, coolero, filen and geeqie in about two hours studing a way to download some of them (geeqie was the more difficult), but in the end nothing is impossible.

In the next days I'll try to provide the apps listed above. Now the database has 1386 apps.

**Comment by ivan-hc** [comment]
UPDATE, all the apps are added to the database!

The download links, tags and icons are all in place, I only tested if the download links and the update scripts are working correctly.

Now we have 1395 voices in the list.

Thanks and sorry for the long wait.
