### ISSUE TITLE
Suggestion of new AppImages to put in the REPO

### ISSUE THREAD

**Issue by edersongs2905** [ivan-hc/AM-Application-Manager#90]
I'd like to suggest some AppImage Apps to the REPO:

mGBA (Game Boy Advance Emulator)
https://github.com/mgba-emu/mgba

G-Desktop-Suite (Google Suite as a desktop app. Made possible with Electron)
https://github.com/alexkim205/G-Desktop-Suite

MS-365-Electron (Unofficial Microsoft 365 Web Desktop Wrapper made with Electron)
https://github.com/agam778/MS-365-Electron

Lunar Client (The #1 Free Minecraft Client - A modpack for all versions of Minecraft) 
https://www.lunarclient.com/download

TLauncher 
https://tlauncher.org

onlyoffice and lunar-client install aren´t working cause it doesn´t download the AppImages
westeroscraftlauncher not working after install

**Comment by ivan-hc** [comment]
Hi @edersongs2905 and thank you.

I miss `mgba`, `ms-365-electron` and `gdesktopsuite` so to add them is easy, I'll close this issue with this upload.

About the others: LunarClient already exists as `lunar-client` and about TLauncher, I've not found an Appimage for it, but if you run the command `am -q minecraft` this is the output:
```
 SEARCH RESULTS FOR "MINECRAFT" IN THE LIST OF AVAILABLE PROGRAMS:

◆ blockbench : Editor for boxy models and pixel art textures like Minecraft.
◆ gdlauncher-appimage : Simple, yet powerful Minecraft custom launcher.
◆ helioslauncher : Custom launcher for modded minecraft written in Electron.
◆ minecraft-launcher : Game downloader and launcher for Minecraft.
◆ packsquash : A Minecraft Java Edition resource and data pack optimizer.
◆ prismlauncher : Launcher for Minecraft, manage multiple installations.
◆ sblauncher : Minecraft Launcher.
◆ swc-minecraft-launcher : SWC Minecraft Launcher.
◆ westeroscraftlauncher : Custom launcher for modded Minecraft (game).
◆ x-minecraft-launcher : An Open Source Minecraft Launcher with Modern UX.

```
I don't know if I have already uploaded it, but as you can see, Minecraft-related results are a lot. If you see that it is not listed with another name here, please redirect me on the exact download page of that AppImage you said, thank you again.

**Comment by ivan-hc** [comment]
Uploaded `mgba`, `ms-365-electron` and `gdesktopsuite`

Commit: https://github.com/ivan-hc/AM-Application-Manager/commit/c71660e5bce602a5e0ae088a4aaaf81639db848f

**Comment by edersongs2905** [comment]
onlyoffice and lunar-client install aren´t working cause it doesn´t download the AppImages

**Comment by ivan-hc** [comment]
Also updated the description for `lunar-client` with the one you gave me (I'm not a gamer, I don't know much about Minecraft and related clients).

Commit: https://github.com/ivan-hc/AM-Application-Manager/commit/8d8e7f39eb6fa9d9ff6751c2ab0aeb122ac436b5

**Comment by ivan-hc** [comment]
> onlyoffice and lunar-client install aren´t working cause it doesn´t download the AppImages, just create the folders.

Thank you for the feedback, just corrected both: https://github.com/ivan-hc/AM-Application-Manager/commit/1acf09ae86c74cce01efe6a475f4d1393d1eb517 https://github.com/ivan-hc/AM-Application-Manager/commit/03d573933c0c32339457d2fbbf071910ade4d422
