### ISSUE TITLE
Join effort with AppImageHub

### ISSUE THREAD

**Issue by edersongs2905** [ivan-hc/AM-Application-Manager#91]
Why not to join effort with AppImageHub (https://www.appimagehub.com/) and have only one and bigger REPO for both?

two big REPOs united would be great!

**Comment by ivan-hc** [comment]
Nope, AppimageHub.com and AppImage.github.io are not repositories, they don't offer constant updates and an AppImage managing like this.

AM is a repository of installation scripts inspired to the AUR, it does not contain packages but a way to install them easily and keeps them always updated.

AM does not manages just AppImages, it also manages official releases of Firefox, Blender and other standalone apps.

And AM is already the richest of apps listed, among the three catalogues (more than 1700 apps listed are AppImages). AppImageHub.com have a limited number of apps if compared with AM, the most of them are also outdated, broken and insecure (NOTE, even among the apps managed by AM there are old and abandoned projects, but at least the source is clearly visible, and it is assumed that the user is aware of what he wants to install).

The frontend of the database of AM is https://portable-linux-apps.github.io, each page is open source and contains the links to the main sites of the developers and a preview of each installation script (so the user knows what that script will do on its PC while running it using AM).

AM is always updated, and also if I will die soon or later, each installation script will still continue working offering the latest version of each app and a way to downgrade them (if URLs and APIs will not change in the future). AM for me it's basically a kind of legacy to the open source world.

Finally, I don't like the way Pling services ask for donations to support users, I can understand the creation of pages and uploads by third-paty users, but these users are not always the original developers and end up making money off the work of others. I don't like this way of doing things at all.

**Comment by edersongs2905** [comment]
I understood!

Thank you for the response!
