### ISSUE TITLE
AM updater

### ISSUE THREAD

**Issue by musicfunfan** [ivan-hc/AM-Application-Manager#93]
Hello there, is there a way to update this script. Does a update command exist or something like that?
Or i just re run the installation command? 

If update flag does not exist it will be nice to exist, In case an update is needed. 

I use topgrade and i would like to add this script to the stuff topgrade updates.

**Comment by ivan-hc** [comment]
For some time now I have been considering the possibility of adding a file containing the ID or SHA of the installation script to compare in case of changes to the script. This will probably be an upgrade of the -s option. I'll see what I can do. Until then, the only solution is to reinstall the app.

**Comment by ivan-hc** [comment]
@musicfunfan I think that this new release is good for this issue (at least to keep the user updated about any changes I'll do on the installation scripts).

https://github.com/ivan-hc/AM-Application-Manager/releases/tag/4.4.3

Update and let me know if you like this.
