### ISSUE TITLE
Local AppImage installation

### ISSUE THREAD

**Issue by hertz98** [ivan-hc/AM-Application-Manager#97]
I really like the work done in these huge scripts.

It would be nice if I could install any local AppImage (from disk), in order to make the process more automatic, like zap package manager allow.

At example I have the AppImage of Chrome 94 and Firefox 92, and I would like to install them in a more standard way rather than copy, paste and manually create shortcuts.

**Comment by ivan-hc** [comment]
Hi, all depends on what you mean abour using local appImages.

If you're talking about to drag and drop AppImages and made them "installed" with their launcher and icon, then already exists the option `--launcher`, see it in action:

https://private-user-images.githubusercontent.com/88724353/281789606-c4b889f4-8504-4853-8918-44d52084fe6c.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjcwNjcsIm5iZiI6MTcwMzYyNjc2NywicGF0aCI6Ii84ODcyNDM1My8yODE3ODk2MDYtYzRiODg5ZjQtODUwNC00ODUzLTg5MTgtNDRkNTIwODRmZTZjLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5N2E3ZDJlOTM3NTBiYjRjYWU5NTQ5NDVmMGJiZDdlYzZkMzNjZjc1Zjg1YmI3NGVhMjVhNTU5ZDU5ZmQ3OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HE9EomV0un0ngUIabHSaJivI3sY5m5P7Y2u8sMQgcJw


Else, if you mean installing apps locally and made them always updatabile from a directory you have called as you prefer in your $HOME, just use [AppMan](https://github.com/ivan-hc/AppMan).

You can use the option `--user` and follow all the instructions, else place the script `appman` wherever you want.

AppMan is AM, but without a system-wide installation and a different name.

If this solves your issue, please close this.

**Comment by ivan-hc** [comment]
NOTE: few minutes ago I've improved the option "-c", so if you have removed some AppImages you have previously integrated with the option "--launcher" and want to remove the orphaned launchers, run the command `am -c` to remove them.

**Comment by hertz98** [comment]
Yes, the launcher option is handy, but it's half of the way.

I know is not probably intended to do that by design but AM could "manage" the local files appimages as the downloaded
- Instaliing using `am -i application.AppImage`
- The AppImage is copied to the AM appimage location
- Shortcuts are created

**Comment by hertz98** [comment]
Yes, the `--launcher` option is handy, but it's half of the way.

I know is not probably intended to do that by design but AM could "manage" the local appimages as the downloaded ones (as zap do) in order to keep the system in a cleaner way 


Installing:
- Instaliing using `am -i application.AppImage` or `am -i customPackageName application.AppImage`
- The AppImage is copied to a common directory or similar
- Shortcuts are created
- The application is shown when `am -f`

Uninstalling
- `am -r application`
- removing AppImage and shortcuts


What zap lacks is the ability to choose to install the applications system-wide.

I understand that this would increase he complexity and I know that with this approach it would not be possible to update the packages as the others (except replacing with local ones)

**Comment by ivan-hc** [comment]
No, the goal of AM/AppMan is to provide installed and managed apps with an organized update system, even if the managed Appimages do not have internal update information (only 10% of them use zsync and appimageupdatetool).

The only thing I can recommend to keep the packages "tidy" is to put them all together in one folder and drag them all into the terminal using the "--launcher" option.

As for system-level integration, I don't do that for obvious reasons. There is no point in installing system-wide packages that can be placed anywhere you want.

Personally I use the "--launcher" option when I have very large AppImages, enough to put them in other partitions (see 0ad).

AM/Appman relies on its own package management system, integration as you understand it is just not in my plans. There are already ZAP and GearLever that do this, and I invented AM/AppMan for reasons that the aforementioned apps can't fully cover. I am sorry.
