### ISSUE TITLE
NixOS/Nix Package Manager Support

### ISSUE THREAD

**Issue by Gr-Nobel** [ivan-hc/AM-Application-Manager#98]
Please add nix package manager support

**Comment by ivan-hc** [comment]
I have never installed/used the Nix Package Manager, but I've seen that it has already its own installation script:

https://nixos.org/download

https://releases.nixos.org/nix/nix-2.19.2/install

how should my package manager install that package manager?

Also, my solutions are ment to install/manage Portable Linux Apps, system-wide (AM) or locally (AppMan), while I've seen that Nix needs to create a /nix directory in the root of the file system (I already use /opt, following the Linux Standard Base).

**Comment by ivan-hc** [comment]
Are you talking about this? https://github.com/DavHau/nix-portable

**Comment by DLopezJr** [comment]
@Gr-Nobel We need more information than that. Please be specific in what you are requesting.
